// Built-in note templates.
const NoteTemplates = {
  items: [
    {
      id: 'meeting',
      name: 'Meeting Notes 📝',
      category: 'work',
      content: [
        '# 📝 Meeting: [Topic]',
        '',
        '**Date:** {{date}}',
        '**Time:** {{time}}',
        '**Attendees:**',
        '- ',
        '- ',
        '',
        '## Agenda',
        '1. ',
        '2. ',
        '3. ',
        '',
        '## Discussion Points',
        '- ',
        '',
        '## Action Items',
        '- [ ] ',
        '- [ ] ',
        '- [ ] ',
        '',
        '## Next Meeting',
        '**Date:** ',
        '**Topics:** ',
        '',
        '---',
        '*Notes by {{nickname}}*'
      ].join('\n')
    },
    {
      id: 'daily-journal',
      name: 'Daily Journal 📅',
      category: 'personal',
      content: [
        '# 📅 Daily Journal - {{date}}',
        '',
        '## 🌅 Morning',
        '**Mood:** ',
        '**Goals for today:**',
        '- [ ] ',
        '- [ ] ',
        '- [ ] ',
        '',
        '## Notes & Thoughts',
        '',
        '',
        '## ✅ Accomplishments',
        '- ',
        '',
        '## 🌙 Evening Reflection',
        '**What went well:**',
        '',
        '**What could be better:**',
        '',
        '**Grateful for:**',
        '',
        '---',
        '**Energy Level:** ⭐⭐⭐⭐⭐'
      ].join('\n')
    },
    {
      id: 'todo',
      name: 'Todo List ✅',
      category: 'planning',
      content: [
        '# ✅ Todo - {{date}}',
        '',
        '## 🔥 High Priority',
        '- [ ] ',
        '- [ ] ',
        '',
        '## 📌 Medium Priority',
        '- [ ] ',
        '- [ ] ',
        '',
        '## 💡 Low Priority',
        '- [ ] ',
        '- [ ] ',
        '',
        '## ✅ Completed',
        '- [x] ',
        '',
        '## 📅 Scheduled for Later',
        '- [ ] ',
        '',
        '---',
        '*Last updated: {{datetime}}*'
      ].join('\n')
    },
    {
      id: 'code-snippet',
      name: 'Code Snippet 💻',
      category: 'development',
      content: [
        '# 💻 Code Snippet: [Title]',
        '',
        '**Language:** ',
        '**Purpose:** ',
        '**Date:** {{date}}',
        '',
        '## Code',
        '```javascript',
        '// Your code here',
        '',
        '```',
        '',
        '## Usage',
        '```javascript',
        '// Example usage',
        '',
        '```',
        '',
        '## Notes',
        '- ',
        '',
        '## References',
        '- ',
        '',
        '---',
        '**Tags:** #code #snippet'
      ].join('\n')
    },
    {
      id: 'bug-report',
      name: 'Bug Report 🐛',
      category: 'development',
      content: [
        '# 🐛 Bug Report: [Title]',
        '',
        '**Date:** {{date}}',
        '**Severity:** [ ] Critical [ ] High [ ] Medium [ ] Low',
        '**Status:** [ ] Open [ ] In Progress [ ] Resolved',
        '',
        '## Description',
        '',
        '',
        '## Steps to Reproduce',
        '1. ',
        '2. ',
        '3. ',
        '',
        '## Expected Behavior',
        '',
        '',
        '## Actual Behavior',
        '',
        '',
        '## Environment',
        '- Browser: ',
        '- OS: ',
        '- Version: ',
        '',
        '## Screenshots/Logs',
        '```',
        '',
        '```',
        '',
        '## Solution',
        '- [ ] ',
        '',
        '---',
        '**Reported by:** {{nickname}}'
      ].join('\n')
    },
    {
      id: 'project-planning',
      name: 'Project Planning 🎯',
      category: 'work',
      content: [
        '# 🎯 Project: [Name]',
        '',
        '**Start Date:** {{date}}',
        '**Deadline:** ',
        '**Status:** [ ] Planning [ ] In Progress [ ] Review [ ] Completed',
        '',
        '## Objective',
        '',
        '',
        '## Scope',
        '### In Scope',
        '- ',
        '',
        '### Out of Scope',
        '- ',
        '',
        '## Milestones',
        '- [ ] Milestone 1 - ',
        '- [ ] Milestone 2 - ',
        '- [ ] Milestone 3 - ',
        '',
        '## Resources Needed',
        '- ',
        '',
        '## Risks & Challenges',
        '- ',
        '',
        '## Success Criteria',
        '- ',
        '',
        '---',
        '**Project Lead:** {{nickname}}'
      ].join('\n')
    },
    {
      id: 'learning',
      name: 'Learning Notes 📚',
      category: 'learning',
      content: [
        '# 📚 Learning: [Topic]',
        '',
        '**Date:** {{date}}',
        '**Source:** ',
        '**Category:** ',
        '',
        '## Key Concepts',
        '- ',
        '',
        '## Summary',
        '',
        '',
        '## Code Examples',
        '```',
        '',
        '```',
        '',
        '## Important Points',
        '- 💡 ',
        '- ⚠️ ',
        '- ✅ ',
        '',
        '## Questions',
        '- [ ] ',
        '',
        '## Related Topics',
        '- ',
        '',
        '## Practice Tasks',
        '- [ ] ',
        '- [ ] ',
        '',
        '---',
        '**Tags:** #learning #notes'
      ].join('\n')
    },
    {
      id: 'brainstorming',
      name: 'Brainstorming 💡',
      category: 'thinking',
      content: [
        '# 💡 Brainstorming: [Topic]',
        '',
        '**Date:** {{date}}',
        '**Goal:** ',
        '',
        '## Ideas',
        '1. 💡 ',
        '2. 💡 ',
        '3. 💡 ',
        '',
        '## Pros & Cons',
        '### Idea 1',
        '**Pros:**',
        '- ',
        '',
        '**Cons:**',
        '- ',
        '',
        '## Next Steps',
        '- [ ] ',
        '- [ ] ',
        '',
        '## Resources',
        '- ',
        '',
        '---',
        '*Keep thinking! 🚀*'
      ].join('\n')
    },
    {
      id: 'reading',
      name: 'Book/Article Notes 📖',
      category: 'learning',
      content: [
        '# 📖 Notes: [Title]',
        '',
        '**Author:** ',
        '**Type:** [ ] Book [ ] Article [ ] Video [ ] Podcast',
        '**Date Read:** {{date}}',
        '**Rating:** ⭐⭐⭐⭐⭐',
        '',
        '## Summary',
        '',
        '',
        '## Key Takeaways',
        '1. ',
        '2. ',
        '3. ',
        '',
        '## Favorite Quotes',
        '> ',
        '',
        '## My Thoughts',
        '',
        '',
        '## Action Items',
        '- [ ] ',
        '- [ ] ',
        '',
        '## Related Reading',
        '- ',
        '',
        '---',
        '**Tags:** #reading #notes'
      ].join('\n')
    },
    {
      id: 'weekly-review',
      name: 'Weekly Review 📊',
      category: 'review',
      content: [
        '# 📊 Weekly Review - Week {{week}}',
        '',
        '**Period:** {{date}} - ',
        '**Overall Rating:** ⭐⭐⭐⭐⭐',
        '',
        '## 🎯 Goals Achieved',
        '- [x] ',
        '- [x] ',
        '',
        '## 📈 Progress',
        '**What went well:**',
        '- ',
        '',
        '**What needs improvement:**',
        '- ',
        '',
        '## 📝 Key Learnings',
        '- ',
        '',
        '## 🔥 Highlights',
        '- ',
        '',
        '## 📅 Next Week Goals',
        '- [ ] ',
        '- [ ] ',
        '- [ ] ',
        '',
        '## 💭 Reflections',
        '',
        '',
        '---',
        '*Reviewed by {{nickname}}*'
      ].join('\n')
    },
    {
      id: 'quick-note',
      name: 'Quick Note ⚡',
      category: 'capture',
      content: [
        '# ⚡ Quick Note',
        '',
        '**Date:** {{datetime}}',
        '',
        '---',
        '*Quick capture*'
      ].join('\n')
    },
    {
      id: 'research',
      name: 'Research Notes 🔬',
      category: 'research',
      content: [
        '# 🔬 Research: [Topic]',
        '',
        '**Date:** {{date}}',
        '**Research Question:** ',
        '',
        '## Background',
        '',
        '',
        '## Findings',
        '### Finding 1',
        '**Source:** ',
        '**Summary:** ',
        '',
        '### Finding 2',
        '**Source:** ',
        '**Summary:** ',
        '',
        '## Data/Evidence',
        '- ',
        '',
        '## Analysis',
        '',
        '',
        '## Conclusions',
        '- ',
        '',
        '## Further Research Needed',
        '- [ ] ',
        '',
        '## References',
        '1. ',
        '2. ',
        '',
        '---',
        '**Tags:** #research'
      ].join('\n')
    }
  ],

  async render(content) {
    const now = new Date();
    const nickname = await Storage.getNickname();
    const date = now.toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' });
    const time = now.toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });
    const datetime = `${date}, ${time}`;
    const week = this.getWeekNumber(now);

    return String(content || '')
      .replace(/\{\{date\}\}/g, date)
      .replace(/\{\{time\}\}/g, time)
      .replace(/\{\{datetime\}\}/g, datetime)
      .replace(/\{\{nickname\}\}/g, nickname)
      .replace(/\{\{week\}\}/g, String(week));
  },

  splitTitle(markdown) {
    const lines = String(markdown || '').split('\n');
    const firstHeadingIndex = lines.findIndex(line => /^#\s+/.test(line));
    if (firstHeadingIndex === -1) {
      return { title: '', content: markdown };
    }

    const title = lines[firstHeadingIndex].replace(/^#\s+/, '').trim();
    const before = lines.slice(0, firstHeadingIndex);
    const after = lines.slice(firstHeadingIndex + 1);
    return {
      title,
      content: [...before, ...after].join('\n').replace(/^\n+/, '')
    };
  },

  getWeekNumber(date) {
    const target = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));
    const dayNumber = target.getUTCDay() || 7;
    target.setUTCDate(target.getUTCDate() + 4 - dayNumber);
    const yearStart = new Date(Date.UTC(target.getUTCFullYear(), 0, 1));
    return Math.ceil((((target - yearStart) / 86400000) + 1) / 7);
  }
};
